/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import AutomataFD.*;
import AutomataFND.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import practica3.Manejar;

/**
 *
 * @author Ana
 */
public class Automata extends javax.swing.JPanel {
    
    private Ventana v;
    private File fichero;
    private final int opc;
    private AFD afd;
    private AFND afnd;
    private Manejar m;
    private CrearAFD crearafd;
    private CrearAFND crearafnd;

    /**
     * Creates new form ModoAFD
     */
    public Automata(Ventana v, int opc) {
        initComponents();
        this.v = v;
        this.opc = opc;
        if(opc == 0)
            TituloTxt.setText("AUTOMATA FINITO DETERMINISTA");
        else
            TituloTxt.setText("AUTOMATA FINITO NO DETERMINISTA");
        
        m = new Manejar(opc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rutaTxt = new javax.swing.JTextField();
        TituloTxt = new javax.swing.JLabel();
        BSeleccionar = new javax.swing.JButton();
        cadenaTxt = new javax.swing.JTextField();
        BCrearAutomata = new javax.swing.JButton();
        ScrollPaneAutomata = new javax.swing.JScrollPane();
        automataTxt = new javax.swing.JTextPane();
        ScrollPaneResultado = new javax.swing.JScrollPane();
        resultadoTxt = new javax.swing.JEditorPane();
        BReconocer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BVolver = new javax.swing.JButton();

        rutaTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del fichero a cargar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        TituloTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N

        BSeleccionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BSeleccionar.setText("Seleccionar ...");
        BSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSeleccionarActionPerformed(evt);
            }
        });

        cadenaTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introduce la secuencia a reconocer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        cadenaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadenaTxtActionPerformed(evt);
            }
        });

        BCrearAutomata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BCrearAutomata.setText("Crear autómata");
        BCrearAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearAutomataActionPerformed(evt);
            }
        });

        automataTxt.setEditable(false);
        ScrollPaneAutomata.setViewportView(automataTxt);

        resultadoTxt.setEditable(false);
        ScrollPaneResultado.setViewportView(resultadoTxt);

        BReconocer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BReconocer.setText("RECONOCER SECUENCIA");
        BReconocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReconocerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setText("Autómata");

        BLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BLimpiar.setText("Limpiar");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Log");

        BVolver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BVolver.setText("Volver");
        BVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cadenaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                    .addComponent(rutaTxt))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BCrearAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BReconocer)
                                        .addGap(18, 18, 18)
                                        .addComponent(BVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(433, 433, 433)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BLimpiar)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ScrollPaneAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(ScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TituloTxt)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCrearAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BReconocer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLimpiar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPaneResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(ScrollPaneAutomata))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSeleccionarActionPerformed
         //Creamos el objeto JFileChooser
        JFileChooser fc = new JFileChooser();
        
        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".TXT", "txt");
        
        //Le indicamos el filtro
        fc.setFileFilter(filtro);
        
        //Abrimos la ventana, guardamos la opción seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this); //hay que pasarle un JPanel
        
        //Si el usuario pincha en aceptar
        if(seleccion == JFileChooser.APPROVE_OPTION){
            //Seleccionamos el fichero
            fichero = fc.getSelectedFile();
            //Escribe la ruta del fichero seleccionado en el campo de texto
            rutaTxt.setText(fichero.getAbsolutePath());                
        }
    }//GEN-LAST:event_BSeleccionarActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        resultadoTxt.removeAll(); //elimina todos los componentes de este contenedor
        resultadoTxt.setText("");
        rutaTxt.setText("");
        cadenaTxt.setText("");
        automataTxt.removeAll();
        automataTxt.setText("");
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void BCrearAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearAutomataActionPerformed

        if(opc == 0){
            crearafd = new CrearAFD();
            crearafd.setVisible(true);
        }
        else{
            crearafnd = new CrearAFND();
            crearafnd.setVisible(true);
        }
        
    }//GEN-LAST:event_BCrearAutomataActionPerformed

    private void BReconocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReconocerActionPerformed
        automataTxt.setText("");
        String ruta, rutaImagen ;
        if(opc == 0){
            //si no hay ruta de fichero es porque se ha creado el autómata manualmente
            if(rutaTxt.getText().equals("")){
                ruta = crearafd.getRuta();
            }
            else{
                ruta = rutaTxt.getText();
            }
        }
        else{
            //si no hay ruta de fichero es porque se ha creado el autómata manualmente
            if(rutaTxt.getText().equals("")){
                ruta = crearafnd.getRuta();
            }
            else{
                ruta = rutaTxt.getText();
            }
        }
        
        //creo el autómata
        try {
            m.leerFichero(ruta);
            m.crearFichero();
        } catch (IOException ex) {
            Logger.getLogger(Automata.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Automata.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //insertamos la imagen del autómata
        rutaImagen = m.getOutPath();
        automataTxt.insertIcon(new ImageIcon(rutaImagen));
        
        boolean resultado;
        String cadena = cadenaTxt.getText();
        if(opc == 0){
            afd = m.getAfd();
            resultado = afd.reconocer(cadena);
        }
        else{
            afnd = m.getAfnd();
            resultado = afnd.reconocer(cadena);
        }
        
        cadena = "Cadena de entrada: " + cadena + "\n";
        if(resultado) {
            cadena = cadena + "El autómata reconoció la cadena\n\n";
        } 
        else {
            cadena = cadena + "El autómata no reconoció la cadena\n\n";
        }
        
        resultadoTxt.setText(cadena);
        
    }//GEN-LAST:event_BReconocerActionPerformed

    private void BVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVolverActionPerformed
        v.goToMP();
    }//GEN-LAST:event_BVolverActionPerformed

    private void cadenaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadenaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadenaTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCrearAutomata;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JButton BReconocer;
    private javax.swing.JButton BSeleccionar;
    private javax.swing.JButton BVolver;
    private javax.swing.JScrollPane ScrollPaneAutomata;
    private javax.swing.JScrollPane ScrollPaneResultado;
    private javax.swing.JLabel TituloTxt;
    private javax.swing.JTextPane automataTxt;
    private javax.swing.JTextField cadenaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JEditorPane resultadoTxt;
    private javax.swing.JTextField rutaTxt;
    // End of variables declaration//GEN-END:variables
}
