/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import AutomataFND.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pc
 */
public class CrearAFND extends javax.swing.JFrame {
    private File fautomata;
    private String ruta;
    private BufferedWriter salidaAutomata;
    private int clicks;
    
    /**
     * Creates new form CrearAFND
     */
    public CrearAFND() {
        initComponents();
        this.setLayout(null);
        clicks = 0;
        ruta = "src\\Ficheros\\AFND.txt";
        //Fichero automata
        fautomata = new File(ruta);
        try {
            salidaAutomata = new BufferedWriter(new FileWriter(fautomata));
        } catch (IOException ex) {
            Logger.getLogger(CrearAFND.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getRuta() {
        return fautomata.getAbsolutePath();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstFinalesTxt = new javax.swing.JLabel();
        estadosFinales = new javax.swing.JTextField();
        origenTxt = new javax.swing.JTextField();
        simboloTxt = new javax.swing.JTextField();
        destinosTxt = new javax.swing.JTextField();
        BAddTransicion = new javax.swing.JButton();
        TransicionesTxt = new javax.swing.JLabel();
        OrigenTitulo = new javax.swing.JLabel();
        SimboloTitulo = new javax.swing.JLabel();
        DestinoTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        origenLambdaTxt = new javax.swing.JTextField();
        destinosLambdaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BAddTransLambda = new javax.swing.JButton();
        BFinalizar = new javax.swing.JButton();
        BAddEstadosFinales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EstFinalesTxt.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        EstFinalesTxt.setText("Estados finales");

        estadosFinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadosFinalesActionPerformed(evt);
            }
        });

        destinosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinosTxtActionPerformed(evt);
            }
        });

        BAddTransicion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BAddTransicion.setText("Añadir");
        BAddTransicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddTransicionActionPerformed(evt);
            }
        });

        TransicionesTxt.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        TransicionesTxt.setText("Transiciones");

        OrigenTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OrigenTitulo.setText("Origen");

        SimboloTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SimboloTitulo.setText("Símbolo");

        DestinoTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DestinoTitulo.setText("Destinos");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel1.setText("Transiciones Lambda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Origen");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Destinos");

        BAddTransLambda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BAddTransLambda.setText("Añadir");
        BAddTransLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddTransLambdaActionPerformed(evt);
            }
        });

        BFinalizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BFinalizar.setText("Finalizar");
        BFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFinalizarActionPerformed(evt);
            }
        });

        BAddEstadosFinales.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BAddEstadosFinales.setText("Hecho");
        BAddEstadosFinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddEstadosFinalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrigenTitulo)
                            .addComponent(origenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SimboloTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simboloTxt))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DestinoTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(destinosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BAddTransLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BAddTransicion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BAddEstadosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(EstFinalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransicionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origenLambdaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(destinosLambdaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(EstFinalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAddEstadosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(TransicionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrigenTitulo)
                    .addComponent(SimboloTitulo)
                    .addComponent(DestinoTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simboloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAddTransicion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinosLambdaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAddTransLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenLambdaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAddTransicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddTransicionActionPerformed
        //agregamos las transiciones
        int origen = Integer.parseInt(origenTxt.getText());
        char simbolo = simboloTxt.getText().charAt(0);
        String[] destinos = destinosTxt.getText().split(",");
        
        //Fichero automata
        try {
            salidaAutomata.write(origen + " " + simbolo + " ");
            int i;
            for(i=0; i<destinos.length-1; i++){
                salidaAutomata.write(destinos[i] + " ");
            }
            salidaAutomata.write(destinos[i] + "\n");
        } catch (IOException ex) {
            Logger.getLogger(CrearAFND.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //limpiamos los valores introducidos
        origenTxt.setText("");
        simboloTxt.setText("");
        destinosTxt.setText("");
    }//GEN-LAST:event_BAddTransicionActionPerformed

    private void BAddEstadosFinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddEstadosFinalesActionPerformed
        String[] finales = estadosFinales.getText().split(",");
        
        //Fichero automata
        try {
            salidaAutomata.write("EF: ");
            int i;
            for(i=0; i<finales.length-1; i++){
                salidaAutomata.write(finales[i] + " ");
            }
            salidaAutomata.write(finales[i] + "\n");
            salidaAutomata.write("T\n");
        } catch (IOException ex) {
            Logger.getLogger(CrearAFND.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BAddEstadosFinalesActionPerformed

    private void estadosFinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadosFinalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadosFinalesActionPerformed

    private void destinosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinosTxtActionPerformed

    private void BAddTransLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddTransLambdaActionPerformed
        int origen = Integer.parseInt(origenLambdaTxt.getText());
        String[] destinos = destinosLambdaTxt.getText().split(",");

        //Fichero automata        
        try {
            clicks++;
            if(clicks == 1){
                salidaAutomata.write("L\n");
            }   
            salidaAutomata.write(origen + " ");
            int i;
            for(i=0; i<destinos.length-1; i++){
                salidaAutomata.write(destinos[i] + " ");
            }
            salidaAutomata.write(destinos[i] + "\n");
        } catch (IOException ex) {
            Logger.getLogger(CrearAFND.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        //limpiamos
        origenLambdaTxt.setText("");
        destinosLambdaTxt.setText("");
    }//GEN-LAST:event_BAddTransLambdaActionPerformed

    private void BFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFinalizarActionPerformed
        try {
            if(clicks == 0){
                salidaAutomata.write("L\n");
            }
            salidaAutomata.write("EOF");
            salidaAutomata.close();
        } catch (IOException ex) {
            Logger.getLogger(CrearAFND.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BFinalizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAddEstadosFinales;
    private javax.swing.JButton BAddTransLambda;
    private javax.swing.JButton BAddTransicion;
    private javax.swing.JButton BFinalizar;
    private javax.swing.JLabel DestinoTitulo;
    private javax.swing.JLabel EstFinalesTxt;
    private javax.swing.JLabel OrigenTitulo;
    private javax.swing.JLabel SimboloTitulo;
    private javax.swing.JLabel TransicionesTxt;
    private javax.swing.JTextField destinosLambdaTxt;
    private javax.swing.JTextField destinosTxt;
    private javax.swing.JTextField estadosFinales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField origenLambdaTxt;
    private javax.swing.JTextField origenTxt;
    private javax.swing.JTextField simboloTxt;
    // End of variables declaration//GEN-END:variables
}
