/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class MenuPrincipal extends javax.swing.JPanel {

    private Ventana v;
    
    /**
     * Creates new form Seleccion
     */
    public MenuPrincipal(Ventana v) {
        initComponents();
        this.v = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BAFD = new javax.swing.JButton();
        BAFND = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        TituloTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 550));

        BAFD.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        BAFD.setText("AUTOMATA AFD");
        BAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAFDActionPerformed(evt);
            }
        });

        BAFND.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        BAFND.setText("AUTOMATA AFND");
        BAFND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAFNDActionPerformed(evt);
            }
        });

        BSalir.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        BSalir.setText("SALIR");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        TituloTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        TituloTxt.setText("Práctica 3: AFD y AFND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TituloTxt)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BAFD, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(BAFND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(TituloTxt)
                .addGap(69, 69, 69)
                .addComponent(BAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(BAFND, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        int valor = JOptionPane.showConfirmDialog(v.getRootPane(), "¿Desea cerrar la aplicación?", "Warning", JOptionPane.YES_NO_OPTION);
        if(valor == JOptionPane.YES_OPTION){
            v.dispose(); //ciera el JFrame
        }
    }//GEN-LAST:event_BSalirActionPerformed

    private void BAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAFDActionPerformed
        v.goToAFD();
    }//GEN-LAST:event_BAFDActionPerformed

    private void BAFNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAFNDActionPerformed
        v.goToAFND();
    }//GEN-LAST:event_BAFNDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAFD;
    private javax.swing.JButton BAFND;
    private javax.swing.JButton BSalir;
    private javax.swing.JLabel TituloTxt;
    // End of variables declaration//GEN-END:variables
}
